name: Code Review
permissions:
  contents: read
  pull-requests: write
on:
  pull_request_review_comment:
    types: [created, deleted]

 

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
    - name: OpenAI ChatGPT Code Review
      uses: Sample-code-review-github-action@v1.0.0
      with:
        PROGRAMMING_LANGUAGE: 'JavaScript'
        OPENAI_TOKEN: ${{ secrets.OPENAI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FULL_REVIEW_COMMENT: 'chatgpt'
        REVIEW_COMMENT_PREFIX: 'chatgpt:'
